manifest:
  defaults:
    remote: zephyrproject-rtos

  self:
    path: app

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: nick-kraus
      url-base: git@github.com:nick-kraus

  projects:
    - name: zephyr
      revision: v3.3.0
      west-commands: scripts/west-commands.yml

    # projects below are lifted from zephyr 88cf0ad506 west.yml, with unused projects removed
    - name: hal_atmel
      revision: d45adfb6897aba323cac29cdda8070ce4f23f014
      path: modules/hal/atmel

    - name: hal_stm32
      revision: b916f9a01c665194fbbdd6a67a0f37b4e0a7e78c
      path: modules/hal/stm32

    - name: cmsis
      revision: 74981bf893e8b10931464b9945e2143d99a3f0a3
      path: modules/hal/cmsis

    - name: mbedtls
      revision: 6e166050075688fd3cf3d0cb3fc34a1c52df2496
      path: modules/crypto/mbedtls

    - name: mcuboot
      revision: 750678e33819b95756203e5db1ba827baee35708
      path: bootloader/mcuboot

    - name: picolibc
      path: modules/lib/picolibc
      revision: 98e59b70d6ef8eb18f7dccc3d39cecaa0658fa4f

    - name: segger
      revision: e2ff2200556e8a8f962921444275c04971a2bb3d
      path: modules/debug/segger
