manifest:
  defaults:
    remote: zephyrproject-rtos

  self:
    path: app

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: nick-kraus
      url-base: git@github.com:nick-kraus

  projects:
    - name: riceprobe-test
      remote: nick-kraus
      revision: b2bd20ba178839737e8197092da7f4bc557a77ce
      path: test

    - name: zephyr
      remote: nick-kraus
      revision: 88cf0ad5065771866504e1482280cf53560c4d82
      west-commands: scripts/west-commands.yml

    # projects below are lifted from zephyr 88cf0ad506 west.yml, with unused projects removed
    - name: hal_atmel
      revision: 43c73d862a78cd5a18a6e24b58cf6980016dbe9e
      path: modules/hal/atmel

    - name: hal_stm32
      revision: 642e199c59828137dc6b1c7044a289d4269886d1
      path: modules/hal/stm32

    - name: cmsis
      revision: 093de61c2a7d12dc9253daf8692f61f793a9254a
      path: modules/hal/cmsis

    - name: mbedtls
      revision: 7fed49c9b9f983ad6416986661ef637459723bcb
      path: modules/crypto/mbedtls

    - name: mcuboot
      revision: cfec947e0f8be686d02c73104a3b1ad0b5dcf1e6
      path: bootloader/mcuboot

    - name: picolibc
      path: modules/lib/picolibc
      revision: 04ada5951cbaf8e7b17f8226ce31cb6837c28ba7

    - name: segger
      revision: d4e568a920b4bd087886170a5624c167b2d0665e
      path: modules/debug/segger
