manifest:
  defaults:
    remote: zephyrproject-rtos

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: nick-kraus
      url-base: git@github.com:nick-kraus

  projects:
    - name: zephyr
      revision: 147cef6
      path: firmware/modules/zephyr
      west-commands: scripts/west-commands.yml

    # projects below are lifted from zephyr 147cef6 west.yml, with unused projects removed
    - name: hal_atmel
      revision: 5ab43007eda3f380c125f957f03638d2e8d1144d
      path: firmware/modules/hal/atmel

    - name: hal_stm32
      revision: 89ef0a3383edebf661073073bcdf6e2836fe90ee
      path: firmware/modules/hal/stm32

    - name: cmsis
      revision: 5a00331455dd74e31e80efa383a489faea0590e3
      path: firmware/modules/hal/cmsis

    - name: mbedtls
      revision: c38dc78d9a8dcbe43b898cc1171ab33ba3e6fc26
      path: firmware/modules/crypto/mbedtls

    - name: mcuboot
      revision: 4fe28b3cf6d30c3e57d6a4f7ee3dba8617aa9a0a
      path: firmware/modules/mcuboot

    - name: picolibc
      revision: d07c38ff051386f8e09a143ea0a6c1d6d66dd1d8
      path: firmware/modules/lib/picolibc

    - name: segger
      revision: 9d0191285956cef43daf411edc2f1a7788346def
      path: firmware/modules/debug/segger
