manifest:
  defaults:
    remote: zephyrproject-rtos

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: nick-kraus
      url-base: https://github.com/nick-kraus

  projects:
    - name: zephyr
      revision: 063ce9caf54fa656f02ae48f3c9d537659a10dec
      path: firmware/modules/zephyr
      west-commands: scripts/west-commands.yml

    # projects below are lifted from zephyr 063ce9caf5 west.yml, with unused projects removed
    - name: hal_atmel
      revision: 942d664e48f7a2725933a93facc112b87b1de32b
      path: firmware/modules/hal/atmel

    - name: hal_stm32
      revision: 89ef0a3383edebf661073073bcdf6e2836fe90ee
      path: firmware/modules/hal/stm32

    - name: cmsis
      revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
      path: firmware/modules/hal/cmsis

    - name: mbedtls
      revision: 7053083b0cff8462464e3cbb826e87852fc03da6
      path: firmware/modules/crypto/mbedtls

    - name: mcuboot
      revision: 0c0470e294dcfb52aab92299356a5f3caa0aa52b
      path: firmware/modules/mcuboot

    - name: picolibc
      revision: d07c38ff051386f8e09a143ea0a6c1d6d66dd1d8
      path: firmware/modules/lib/picolibc

    - name: segger
      revision: 9d0191285956cef43daf411edc2f1a7788346def
      path: firmware/modules/debug/segger
